# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/01_Xilinx_FPGA/00_BasicMicroblaze/MyIP/AXI_OLED_SSD1306/AXI_OLED_SSD1306/AXI_OLED_SSD1306.cache/wt [current_project]
set_property parent.project_path D:/01_Xilinx_FPGA/00_BasicMicroblaze/MyIP/AXI_OLED_SSD1306/AXI_OLED_SSD1306/AXI_OLED_SSD1306.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/01_Xilinx_FPGA/00_BasicMicroblaze/MyIP/AXI_OLED_SSD1306/AXI_OLED_SSD1306/AXI_OLED_SSD1306.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/01_Xilinx_FPGA/00_BasicMicroblaze/MyIP/AXI_OLED_SSD1306/IPSRC/charLib/charLib.coe
read_verilog -library xil_defaultlib {
  D:/01_Xilinx_FPGA/00_BasicMicroblaze/MyIP/AXI_OLED_SSD1306/IPSRC/Delay.v
  D:/01_Xilinx_FPGA/00_BasicMicroblaze/MyIP/AXI_OLED_SSD1306/IPSRC/SSD1306_OLED_v1_0_S00_AXI.v
  D:/01_Xilinx_FPGA/00_BasicMicroblaze/MyIP/AXI_OLED_SSD1306/IPSRC/SpiCtrl.v
  D:/01_Xilinx_FPGA/00_BasicMicroblaze/MyIP/AXI_OLED_SSD1306/IPSRC/SSD1306_OLED_ML.v
}
read_ip -quiet d:/01_Xilinx_FPGA/00_BasicMicroblaze/MyIP/AXI_OLED_SSD1306/IPSRC/charLib/charLib/charLib.xci
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/00_BasicMicroblaze/MyIP/AXI_OLED_SSD1306/IPSRC/charLib/charLib/charLib_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top SSD1306_OLED_ML -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SSD1306_OLED_ML.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SSD1306_OLED_ML_utilization_synth.rpt -pb SSD1306_OLED_ML_utilization_synth.pb"
